export const rows = [
    {
      id: 1,
      Name: "John Doe",
      Email: "johndoe@example.com",
      Age: 29,
      Phone: "123-456-7890",
      Address: "123 Main St",
      City: "New York",
      zipCode: "10001",
      registrarId: "A123",
    },
    {
      id: 2,
      Name: "Jane Smith",
      Email: "janesmith@example.com",
      Age: 34,
      Phone: "987-654-3210",
      Address: "456 Oak St",
      City: "Los Angeles",
      zipCode: "90001",
      registrarId: "B456",
    },
    {
      id: 3,
      Name: "Michael Johnson",
      Email: "michaelj@example.com",
      Age: 41,
      Phone: "456-789-0123",
      Address: "789 Pine St",
      City: "Chicago",
      zipCode: "60601",
      registrarId: "C789",
    },
    {
      id: 4,
      Name: "Emily Davis",
      Email: "emilyd@example.com",
      Age: 27,
      Phone: "321-654-0987",
      Address: "101 Maple Ave",
      City: "Houston",
      zipCode: "77001",
      registrarId: "D234",
    },
    {
      id: 5,
      Name: "Robert Brown",
      Email: "robertb@example.com",
      Age: 36,
      Phone: "654-321-7890",
      Address: "222 Birch Rd",
      City: "San Francisco",
      zipCode: "94101",
      registrarId: "E567",
    },
    {
      id: 6,
      Name: "Sarah Wilson",
      Email: "sarahw@example.com",
      Age: 31,
      Phone: "789-012-3456",
      Address: "333 Cedar Ln",
      City: "Seattle",
      zipCode: "98101",
      registrarId: "F890",
    },
    {
      id: 7,
      Name: "David Martinez",
      Email: "davidm@example.com",
      Age: 45,
      Phone: "987-123-4567",
      Address: "444 Willow Dr",
      City: "Denver",
      zipCode: "80201",
      registrarId: "G123",
    },
    {
      id: 8,
      Name: "Laura Taylor",
      Email: "laurat@example.com",
      Age: 28,
      Phone: "123-789-4560",
      Address: "555 Elm St",
      City: "Boston",
      zipCode: "02101",
      registrarId: "H456",
    },
    {
      id: 9,
      Name: "Daniel Anderson",
      Email: "daniela@example.com",
      Age: 39,
      Phone: "321-098-7654",
      Address: "666 Spruce Blvd",
      City: "Phoenix",
      zipCode: "85001",
      registrarId: "I789",
    },
    {
      id: 10,
      Name: "Sophia Thomas",
      Email: "sophiat@example.com",
      Age: 33,
      Phone: "654-789-0123",
      Address: "777 Redwood St",
      City: "Miami",
      zipCode: "33101",
      registrarId: "J234",
    },
    {
      id: 11,
      Name: "James White",
      Email: "jamesw@example.com",
      Age: 37,
      Phone: "789-321-6540",
      Address: "888 Cypress Ct",
      City: "Dallas",
      zipCode: "75201",
      registrarId: "K567",
    },
  ];
  